v1.0.0
shestooy/ToDo-REST pull request #1
Opened 2024-06-22 12:01 UTC by shestooy

- initial commit
// Данная репа - перезалив, в первый раз запорол репу, но само задание выполнил, поэтому перезалил.

2024-06-22 12:56 UTC, just-musha requested changes
Привет! Хорошая работа, подробные комментарии, все ошибки обработаны - вижу что удалось разобраться в теме. Отправлю пачку комментариев - главный из которых добавить проверку id  в методе AddNewTask, остальное по желанию. Жду правки

2024-06-22 12:56 UTC, just-musha commented on precode.go
> +// Лишь в одном обработчике, который возвращает код 201.
Валидно :+1:

2024-06-22 12:56 UTC, just-musha commented on precode.go
> +	tasks[newTask.ID] = newTask
Перед этим полезно проверить, есть ли уже такой id. Иначе задача будет перезатерта. Если есть - вернуть ошибку пользователю

2024-06-22 12:56 UTC, just-musha commented on precode.go
> +	if _, ok := tasks[id]; ok == false {
```diff
-ok== false
+!ok
```

2024-06-22 12:56 UTC, just-musha commented on precode.go
> +		http.Error(res, "задача с данным ID не найдена", http.StatusBadRequest) //?
В чем здесь вопрос? Все ок

2024-06-22 12:56 UTC, just-musha commented on precode.go
> +	res.Header().Set("Content-Type", "application/json")
Это не нужно, тело ответа пустое

2024-06-22 12:56 UTC, just-musha commented on precode.go
> +	r.Get("/tasks", GetTasksHandler)
Можно ещё названия причесать хендлеров, более единообразно

GetTasks ?

2024-06-22 12:56 UTC, just-musha commented on precode.go
> +	r.Post("/tasks", AddNewTask)
PostTask

2024-06-22 12:56 UTC, just-musha commented on precode.go
> +	if _, ok := tasks[id]; ok == false {
```diff
-ok== false
+!ok
```

2024-06-22 12:56 UTC, just-musha commented on precode.go
> +		http.Error(res, err.Error(), http.StatusBadRequest)
Здесь достаточно просто залогировать ошибку, тк ошибка случилась при вызове Write - то записать уже вряд ли получится (http.Error все равно внутри пытается вызвать Write). Поэтомму просто логируем

2024-06-22 12:56 UTC, just-musha commented on precode.go
> +	_, err = res.Write(jsonSlice)
Круто что не забываешь про эту ошибку

2024-06-22 12:56 UTC, just-musha commented on precode.go
> +		http.Error(res, err.Error(), http.StatusInternalServerError)
Здесь тоже достаточно залогировать (ниже объяснила)

2024-06-22 13:19 UTC, shestooy commented
Привет, прошелся по всем замечаниям, поправил

2024-06-22 18:06 UTC, just-musha requested changes
Фатал только не нужен, а в остальном все верно!

2024-06-22 18:06 UTC, just-musha commented on precode.go
> +		log.Fatal(err)
Фатал остановит сервер - это здесь не нужно, достаточно её просто напечатать

2024-06-22 18:06 UTC, just-musha commented on precode.go
> +		http.Error(res, "запись с таким id уже есть", http.StatusBadRequest)
Отлично

2024-06-22 18:06 UTC, just-musha commented on precode.go
> +		log.Fatal(err.Error())
```diff
-Fatal
+Println
```

2024-06-23 18:07 UTC, just-musha requested changes
Остался 1 момент, с ним не могу принять, критично

2024-06-23 18:07 UTC, just-musha commented on precode.go
> +		log.Fatal(err)
Fatal тут тоже не нужен

2024-06-23 19:03 UTC, just-musha approved these changes
Ес, спасибо за быстрый фикс! Принято!

2024-06-23 19:21 UTC, merged